/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package capgemini;
import java.util.Scanner; 

public class App {
    
    

    public static void main(String[] args) {
        
        Scanner input = new Scanner(System.in);

        String nome = input.nextLine();
        int idade = input.nextInt();
        float cotacaoDolar = input.nextFloat();

        System.out.print(nome);
        

    }
}
